export const lightColors = {
  primary: '#1A73E8',
  primaryDark: '#0D47A1',
  primaryLight: '#E8F0FE',
  background: '#F8F9FF',
  surface: '#FFFFFF',
  text: '#1C1C1E',
  textSecondary: '#6E6E73',
  border: '#E0E0E0',
  accent: '#E8F0FE',
  error: '#D32F2F',
  errorBg: '#FFEBEE',
  errorText: '#B71C1C',
  networkErrorBg: '#FFF3E0',
  networkErrorBorder: '#E65100',
  inputBorder: '#DADCE0',
  inputFocusBorder: '#1A73E8',
  inputBackground: '#FAFAFA',
  inputFocusedBackground: '#FFFFFF',
  inputErrorBackground: '#FFF8F8',
  placeholder: '#ABABAB',
  chipBorder: '#C5D8FB',
  exampleBackground: '#F8F9FF',
  cardShadow: '#000000',
  statusBar: 'light-content',
  noun: '#1565C0',
  nounBg: '#E3F2FD',
  verb: '#6A1B9A',
  verbBg: '#F3E5F5',
  adjective: '#E65100',
  adjectiveBg: '#FFF3E0',
  adverb: '#2E7D32',
  adverbBg: '#E8F5E9',
  other: '#37474F',
  otherBg: '#ECEFF1',
  switchTrackFalse: '#DADCE0',
  switchTrackTrue: '#1A73E8',
};

export const darkColors = {
  primary: '#1A73E8',
  primaryDark: '#93C5FD',
  primaryLight: '#1E3A5F',
  background: '#0B1220',
  surface: '#151F33',
  text: '#F1F5F9',
  textSecondary: '#94A3B8',
  border: '#2A3548',
  accent: '#1E3A5F',
  error: '#F87171',
  errorBg: '#3B1F1F',
  errorText: '#FCA5A5',
  networkErrorBg: '#3B2F1A',
  networkErrorBorder: '#FB923C',
  inputBorder: '#334155',
  inputFocusBorder: '#1A73E8',
  inputBackground: '#1A2332',
  inputFocusedBackground: '#1E293B',
  inputErrorBackground: '#3B1F1F',
  placeholder: '#64748B',
  chipBorder: '#2563EB',
  exampleBackground: '#1A2332',
  cardShadow: '#000000',
  statusBar: 'light-content',
  noun: '#60A5FA',
  nounBg: '#1E3A5F',
  verb: '#C084FC',
  verbBg: '#2D1B4E',
  adjective: '#FB923C',
  adjectiveBg: '#3B2F1A',
  adverb: '#4ADE80',
  adverbBg: '#1A3B2A',
  other: '#94A3B8',
  otherBg: '#1E293B',
  switchTrackFalse: '#334155',
  switchTrackTrue: '#1A73E8',
};

export const getPartOfSpeechColor = (pos, colors) => {
  const map = {
    noun: { text: colors.noun, bg: colors.nounBg },
    verb: { text: colors.verb, bg: colors.verbBg },
    adjective: { text: colors.adjective, bg: colors.adjectiveBg },
    adverb: { text: colors.adverb, bg: colors.adverbBg },
  };
  return map[pos?.toLowerCase()] || { text: colors.other, bg: colors.otherBg };
};
